file(READ "${PROJECT_ROOT}/docs/assets/asset-sources.md" manifest)
file(GLOB_RECURSE assets RELATIVE "${PROJECT_ROOT}" "${PROJECT_ROOT}/assets/*.png")
foreach(asset IN LISTS assets)
  string(FIND "${manifest}" "${asset}" found)
  if(found EQUAL -1)
    message(FATAL_ERROR "Asset is missing provenance row: ${asset}")
  endif()
endforeach()
if(NOT assets)
  message(FATAL_ERROR "No traced visual assets found")
endif()
message(STATUS "Asset provenance passed for ${assets}")
