file(GLOB_RECURSE MODEL_FILES "${PROJECT_ROOT}/src/model/*")
file(GLOB_RECURSE VIEWMODEL_FILES "${PROJECT_ROOT}/src/viewmodel/*")
file(GLOB_RECURSE VIEW_FILES "${PROJECT_ROOT}/src/view/*")
set(APP_BINDING_FILE "${PROJECT_ROOT}/src/app/Application.cpp")

function(reject_matches label pattern)
  foreach(path IN LISTS ARGN)
    file(READ "${path}" text)
    if(text MATCHES "${pattern}")
      message(FATAL_ERROR "${label}: ${path}")
    endif()
  endforeach()
endfunction()

function(require_match label pattern path)
  file(READ "${path}" text)
  if(NOT text MATCHES "${pattern}")
    message(FATAL_ERROR "${label}: ${path}")
  endif()
endfunction()

reject_matches("Model depends on SFML/View/ViewModel" "#[ \t]*include[ \t]*[<\"](SFML|viewmodel/|view/)" ${MODEL_FILES})
reject_matches("Model knows a ViewModel symbol" "viewmodel::|namespace[ \t]+isaac::viewmodel" ${MODEL_FILES})
reject_matches("ViewModel depends on View/SFML" "#[ \t]*include[ \t]*[<\"](SFML|view/)" ${VIEWMODEL_FILES})
reject_matches("ViewModel includes a concrete Model implementation" "#[ \t]*include[ \t]*[<\"]model/(GameSession|CharacterCatalog|Player)\\.h" ${VIEWMODEL_FILES})
reject_matches("ViewModel reaches into concrete Model internals" "session_\\.player\\(|model::GameSession[ \t]*[&*]" ${VIEWMODEL_FILES})
reject_matches("View directly depends on Model" "#[ \t]*include[ \t]*[<\"]model/" ${VIEW_FILES})
reject_matches("View directly depends on ViewModel" "#[ \t]*include[ \t]*[<\"]viewmodel/|viewmodel::|GameViewModel" ${VIEW_FILES})
reject_matches("View selects presentation resources with Model strings" "styleId|selectionName[ \t]*==" ${VIEW_FILES})
reject_matches("ViewModel exposes grouped bindings" "GameProperties|GameCommands|GameSignals|properties\\(\\)|commands\\(\\)|signals\\(\\)" ${VIEWMODEL_FILES})

require_match("App does not bind the display Property" "displayProperty\\(\\).*changed\\(\\).*connect" "${APP_BINDING_FILE}")
require_match("App does not bind the action Command" "setActionHandler" "${APP_BINDING_FILE}")
require_match("App does not bind the input Command" "setInputHandler" "${APP_BINDING_FILE}")
require_match("App does not bind the presentation Signal" "presentationSignal\\(\\).*connect" "${APP_BINDING_FILE}")

file(READ "${PROJECT_ROOT}/CMakeLists.txt" CMAKE_TEXT)
if(CMAKE_TEXT MATCHES "target_link_libraries\\(isaac_view[ \t\r\n][^\\)]*isaac_viewmodel")
  message(FATAL_ERROR "View target links the concrete ViewModel target")
endif()
message(STATUS "Strict MVVM architecture check passed")
